# Generated by Django 3.2.13 on 2023-03-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20230304_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isSold',
            new_name='sold',
        ),
    ]
